stages:
    - build
    - deploy

build-back:
    stage: build
    only :
        - master
        - develop
    script :
        - cd $CI_PROJECT_DIR/backend
        - chmod +x mvnw
        - ./mvnw package
        - cp target/*.jar ~/app1.jar
    tags : 
    # !! tag 값이 동일하게 설정된 Runner만 파이프라인을 동작시킴
    # 여러 서버에 배포할때 서버별 runner 태그로도 활용(dev, stg, prd)
    - prd

build-front:
    stage: build
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - frontend/node_modules
    only :
        - master
        - develop
    script :
        - cd $CI_PROJECT_DIR/frontend
        - npm install
        - npm run build
    tags :
        - prd

deploy-back:
    stage: deploy
    only :
        - master
        - develop
    script :
        - cd $HOME/backend
        - ~/restart_backend1.sh
    tags : 
        - prd

deploy-front:
    stage: deploy
    only :
        - master
        - develop
    script :
        # 배포는 이미 끝나서 단순 확인하기 위한 job으로만 구성
        - ls -al /home/ubuntu/SubPJT3/S05P13C102/frontend/dist
    tags :
        - prd
